### ISSUE TITLE
Missing element on line 43 of the VoronoiPrecise3D led to weird creasing along the z axis.

### ISSUE THREAD

**Issue by maxtarabbia** [JimmyCushnie/Noisy-Nodes#11]
Line 43 used to read "_if (cellDifference.x + cellDifference.y > 0.1){_" which led to weird creasing, which was most noticeable when the Angle Offset was set to 0.

Changing it to "_if (cellDifference.x + cellDifference.y + cellDifference.z > 0.1){_" eliminates this issue and make the VoronoiPrecise 3D uniform across all 3 dimensions.

**Comment by JimmyCushnie** [comment]
Hey, I'm really sorry it took me 6 months to get to this. Had a bit of a rough start to the year.

Thanks so much for bringing this up! You're entirely correct about the problem and the solution. Fixed, in the commit referenced above.

Here's before the fix:

![image](https://user-images.githubusercontent.com/32693298/126691369-666c22a7-2c55-4463-815a-602e05aec496.png)

And here's after the fix:

![image](https://user-images.githubusercontent.com/32693298/126691316-8b6e18a1-0e65-407c-808d-4c5133fd98ee.png)
