### ISSUE TITLE
Remove asmdef from package

### ISSUE THREAD

**Issue by rhys-vdw** [JimmyCushnie/Noisy-Nodes#13]
As this project contains no C#, it does not require an asmdef. Its presence causes repeated warnings on compilation.

Warning on compile:
```
Assembly for Assembly Definition File 'Packages/com.jimmycushnie.noisynodes/NoisyNodes.asmdef' will not be compiled, because it has no scripts associated with it.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,string[])
```

**Comment by JimmyCushnie** [comment]
Hm, I don't get that on 2019.4.40f1. Which version of Unity are you in?

It's my understanding that all packages are required to have an assembly definition, even if they don't have any C#. However I could be wrong, or this could have changed since I learned the rule.

**Comment by rhys-vdw** [comment]
> Hm, I don't get that on 2019.4.40f1. Which version of Unity are you in?

2021.3.2f

> It's my understanding that all packages are required to have an assembly definition, even if they don't have any C#. However I could be wrong, or this could have changed since I learned the rule.

I considered this might be the reason, however I doubt it's the case if there is no assembly to define. I'll probably end up forking and checking this, so I'll open a PR or update here depending on result (assuming you don't beat me to it).

**Comment by JimmyCushnie** [comment]
By all means, please do the work for me :P

**Comment by AVAVT** [comment]
Please I need this update. Our project is now clean with only 1 warning from this issue printed every compile 🙏🏼 

![image](https://user-images.githubusercontent.com/5208782/208651289-bf84a70b-e696-46f9-88e2-276b6495d37f.png)

**Comment by rhys-vdw** [comment]
> Please I need this update. Our project is now clean with only 1 warning from this issue printed every compile 🙏🏼

Talk about _noisy_ amirite?

Just use this in your `manifest.json`:

```json
    "com.jimmycushnie.noisynodes": "https://github.com/EffortStar/Noisy-Nodes.git#13-remove-asmdef",
```
